language: node_js
node_js:
- "10"
- "8"

before_install:
- npm install --global npm@latest
- npm install --global yarn@latest
- npm install --global lerna@latest

install:
- lerna bootstrap
- lerna run build

script:
- lerna run test